"""second migration added foreign keys and book relationship

Revision ID: 59dc8d86d61f
Revises: 8f1355810c93
Create Date: 2021-09-16 20:52:58.415191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59dc8d86d61f'
down_revision = '8f1355810c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('book', sa.Column('person_id', sa.Integer(), nullable=True))
    op.drop_constraint('book_user_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'person', ['person_id'], ['id'])
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_user_id_fkey', 'book', 'user', ['user_id'], ['id'])
    op.drop_column('book', 'person_id')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
